# Generated by Django 3.2.12 on 2023-07-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='bitrate',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='resolution',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='audio_channels',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='audio_codec_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='audio_sample_rate',
            field=models.IntegerField(null=True),
        ),
    ]
