# Generated by Django 3.2.12 on 2023-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadapp', '0002_auto_20230713_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='bitrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='resolution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
