# Generated by Django 3.2.12 on 2023-07-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploadapp', '0003_auto_20230713_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='tags',
        ),
    ]
